import { parseWatchlistAssets, type WatchlistAssets } from "./adapters";

/** 原始接口形状（GET /v1/stock-workspaces，contract_version=stock_asset_list_v1）。 */
export function assetsPayload() {
  return {
    contract_version: "stock_asset_list_v1",
    status: "partial",
    items: [
      {
        workspace_id: "ws-000063",
        version: 3,
        symbol: "000063.SZ",
        name: "中兴通讯",
        market: "a_share",
        relation_type: "watching",
        relation_label: "关注",
        priority: "high",
        tracking_status: "active",
        workflow_status: "researching",
        attention_tags: ["算力"],
        active_thesis: { summary: "算力订单兑现节奏是核心变量。", version: 2, watch_items: [], recheck_conditions: [] },
        latest_change: {
          link_id: "l-1",
          event_id: "c-1",
          event_type: "official_financial_disclosure",
          title: "中兴通讯披露半年报",
          summary: "中兴通讯披露半年报，营收同比变化需复核。",
          occurred_at: "2026-08-05T10:00:00+00:00",
          detected_at: "2026-08-05T10:05:00+00:00",
          created_at: "2026-08-05T10:05:00+00:00",
          read_at: null,
          handled_at: null,
          relevance_status: "relevant",
          relevance_status_label: "相关",
          source_name: "Eastmoney Announcements",
          source_url: "https://example.com/c1",
          boundary: null,
        },
        next_action: { title: "复核半年报毛利率变化", next_step: "对比一季报毛利率", status: "pending" },
        open_task_count: 2,
        position_snapshot: { available: false, status: "not_configured" },
        report_meta: {
          id: "r-1",
          symbol: "000063.SZ",
          name: "中兴通讯",
          title: "中兴通讯 每日研究",
          summary: "每日研究快照。",
          status: "ready",
          generated_at: "2026-08-06T06:50:12+00:00",
          market_timestamp: "2026-08-05T01:30:00+00:00",
          source_scope: "server_evidence_snapshot",
          source_scope_label: "服务器公共证据快照",
        },
        report_freshness: { status: "today", label: "今日已更新", is_today: true },
        data_times: {
          quote_as_of: "2026-08-06T06:50:06+00:00",
          daily_as_of: "2026-08-05T01:30:00+00:00",
          financial_report_period: "2026-03-31",
          report_generated_at: "2026-08-06T06:50:12+00:00",
          report_market_timestamp: "2026-08-05T01:30:00+00:00",
        },
        counterevidence: [],
        invalidation_conditions: [],
        next_evidence: [],
        quote: {
          price: 34.69,
          pct_change: -0.14,
          label: "盘中最新报价",
          market_timestamp: "2026-08-06T06:50:06+00:00",
          status: "available",
          currency: "CNY",
        },
        data_status: "ready",
        warnings: [],
      },
      {
        workspace_id: "ws-600519",
        version: 1,
        symbol: "600519.SS",
        name: "贵州茅台",
        market: "a_share",
        relation_type: "watching",
        relation_label: "关注",
        priority: "normal",
        tracking_status: "paused",
        workflow_status: "waiting_data",
        attention_tags: [],
        active_thesis: null,
        latest_change: null,
        next_action: null,
        open_task_count: 0,
        position_snapshot: { available: false, status: "not_configured" },
        report_meta: null,
        report_freshness: { status: "missing", label: "等待生成", is_today: false },
        data_times: {
          quote_as_of: null,
          daily_as_of: null,
          financial_report_period: null,
          report_generated_at: null,
          report_market_timestamp: null,
        },
        counterevidence: [],
        invalidation_conditions: [],
        next_evidence: [],
        quote: {
          price: null,
          pct_change: null,
          label: null,
          market_timestamp: null,
          status: "unavailable",
          currency: null,
        },
        data_status: "partial",
        warnings: ["该股票的行情或研究摘要暂未完整返回"],
      },
      {
        workspace_id: "ws-aapl",
        version: 5,
        symbol: "AAPL",
        name: "Apple Inc.",
        market: "us",
        relation_type: "ended",
        relation_label: "已结束",
        priority: null,
        tracking_status: "active",
        workflow_status: "idle",
        attention_tags: [],
        active_thesis: { summary: "硬件周期判断已完成复盘。", version: 4, watch_items: [], recheck_conditions: [] },
        latest_change: null,
        next_action: null,
        open_task_count: 0,
        position_snapshot: { available: false, status: "not_configured" },
        report_meta: null,
        report_freshness: { status: "missing", label: "等待生成", is_today: false },
        data_times: {
          quote_as_of: null,
          daily_as_of: null,
          financial_report_period: null,
          report_generated_at: null,
          report_market_timestamp: null,
        },
        counterevidence: [],
        invalidation_conditions: [],
        next_evidence: [],
        quote: {
          price: 210.5,
          pct_change: 1.25,
          label: "最新收盘",
          market_timestamp: "2026-08-05T20:00:00+00:00",
          status: "available",
          currency: "USD",
        },
        data_status: "ready",
        warnings: [],
      },
    ],
    summary: { total: 3, watching: 2, holding: 0, ended: 1, paused: 1, waiting_data: 1 },
    boundary: "该列表组织用户的长期股票研究资产；已结束空间仍保留判断、任务和历史。",
  };
}

export function emptyAssetsPayload() {
  return {
    contract_version: "stock_asset_list_v1",
    status: "empty",
    items: [],
    summary: { total: 0, watching: 0, holding: 0, ended: 0, paused: 0, waiting_data: 0 },
    boundary: "该列表组织用户的长期股票研究资产。",
  };
}

export const parsedAssets = (): WatchlistAssets => parseWatchlistAssets(assetsPayload());
