import { type ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import type { Breadth, DataHealth, GlobalIndices, IndexCard, LiveMarkets, Overview, ResearchChanges, ResearchActions, Sectors, WatchlistBrief } from "./adapters";
import { CHART_COLORS, BarChart, DonutChart, Histogram, Sparkline } from "./charts";
import { todayQueries } from "./queries";
import styles from "./TodayPage.module.css";

export function formatDateTime(value: string | null | undefined): string {
  if (!value || Number.isNaN(new Date(value).getTime())) return "时间待确认";
  return new Intl.DateTimeFormat("zh-CN", { timeZone: "Asia/Shanghai", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value));
}
export function formatNumber(value: number | null, digits = 2): string { return value === null ? "暂无" : new Intl.NumberFormat("zh-CN", { minimumFractionDigits: digits, maximumFractionDigits: digits }).format(value); }
function formatCount(value: number | null): string { return value === null ? "暂无" : new Intl.NumberFormat("zh-CN").format(value); }
function percent(value: number | null): string { return value === null ? "暂无" : `${value > 0 ? "+" : ""}${formatNumber(value)}%`; }
function tone(value: number | null): string { return value === null || value === 0 ? styles.flat : value > 0 ? styles.up : styles.down; }
function priorityKind(kind: string): string { return ({ research_action: "研究行动", observation_task: "观察任务", draft_confirmation: "判断草稿", change_event: "重要变化", trade_review: "交易复盘" } as Record<string, string>)[kind] ?? "研究事项"; }
function changeEventType(value: string | null): string { return ({ baseline: "基线建立", evidence_change: "证据变化" } as Record<string, string>)[value ?? ""] ?? "研究更新"; }

export function ModuleCard({ title, meta, pending, error, onRetry, children, className = "" }: { title: string; meta?: ReactNode; pending: boolean; error: boolean; onRetry: () => void; children: ReactNode; className?: string }) {
  return <section className={`${styles.card} ${className}`} aria-label={title}><div className={styles.cardHeader}><h2>{title}</h2>{meta ? <div className={styles.meta}>{meta}</div> : null}</div>{pending ? <div className={styles.skeleton} aria-live="polite">正在读取…</div> : null}{!pending && error ? <div className={styles.moduleError} role="status"><span>本模块暂时不可用，其他内容仍可继续查看。</span><button type="button" onClick={onRetry}>重新读取</button></div> : null}{!pending && !error ? children : null}</section>;
}

export function TodayHeader({ overview, pending, eventState, onRefresh }: { overview?: Overview; pending: boolean; eventState: string; onRefresh: () => void }) {
  const closed = overview?.session.exchangeStatus !== "open";
  const label = eventState === "connected" ? "更新通道已连接" : eventState === "reconnecting" ? "更新通道重连中" : "按需更新";
  return <><header className={styles.hero}><div><h1>今日观察</h1><p>今天市场发生了什么？你应该关注哪些重点信号？</p></div><div className={styles.heroStatus}><span className={`${styles.badge} ${closed ? styles.badgeMuted : styles.badgeLive}`}>{overview?.session.exchangeLabel ?? "交易状态读取中"}</span><span data-testid="today-market-date">{overview?.marketDate ?? "市场日期读取中"}</span><span data-testid="today-generated-at" data-generated-at={overview?.generatedAt ?? ""}>生成 {formatDateTime(overview?.generatedAt)}</span><span>{label}</span><button className={styles.refresh} type="button" onClick={onRefresh}>刷新</button></div></header>{overview?.coverageStatus === "partial" ? <div className={styles.notice} role="status">部分数据暂不可用；已返回模块仍保持可读。</div> : null}{overview && closed ? <div className={styles.notice} role="status">当前为{overview.session.label}，行情展示最近已确认数据，并标注对应市场时间。</div> : null}{overview?.headline ? <div className={styles.notice} role="status">{overview.headline}</div> : pending ? null : null}</>;
}

function IndexCardView({ item, loadHistory }: { item: IndexCard; loadHistory: boolean }) {
  const available = item.status === "available" && item.latestClose !== null;
  const history = useQuery({ ...todayQueries.indexHistory(item.symbol), enabled: loadHistory && available });
  return <article className={styles.indexCard}><div className={styles.indexName}><strong>{item.name}</strong><span>{item.symbol}</span></div>{available ? <><div className={styles.indexQuote}><span className={styles.indexValue}>{formatNumber(item.latestClose)}</span><span className={tone(item.change1d)}>{item.change1d === null ? "暂无" : `${item.change1d > 0 ? "+" : ""}${formatNumber(item.change1d)}`}</span><span className={tone(item.return1dPct)}>{percent(item.return1dPct)}</span></div>{history.data?.closes && history.data.closes.length >= 2 ? <Sparkline values={history.data.closes} /> : null}<small>市场 {formatDateTime(item.marketTimestamp)}{item.isStale === true ? " · 缓存数据" : item.isStale === null ? " · 新鲜度待确认" : ""}</small></> : <div className={styles.emptyCompact}>暂不可用</div>}</article>;
}

export function IndexSection({ items, generatedAt, pending, error, onRetry, loadHistory }: { items: IndexCard[] | undefined; generatedAt: string | null | undefined; pending: boolean; error: boolean; onRetry: () => void; loadHistory: boolean }) {
  return <ModuleCard className={styles.full} title="主要指数" meta={generatedAt ? `更新 ${formatDateTime(generatedAt)}` : undefined} pending={pending} error={error} onRetry={onRetry}><div className={styles.indexGrid}>{items?.map((item) => <IndexCardView item={item} loadHistory={loadHistory} key={item.symbol} />)}</div></ModuleCard>;
}

export function MarketBreadthCard({ data, pending, error, onRetry }: { data?: Breadth; pending: boolean; error: boolean; onRetry: () => void }) { return <ModuleCard title="市场广度" pending={pending} error={error} onRetry={onRetry}>{data?.status === "available" ? <><div className={styles.breadthLead}><strong>{data.state ?? "市场状态待确认"}</strong><span>{data.marketDate ?? "日期待确认"}{data.isStale === true ? " · 非实时" : data.isStale === null ? " · 新鲜度待确认" : ""}</span></div><div className={styles.donutWrap}><DonutChart segments={[{ label: "上涨", value: data.advancers ?? 0, color: CHART_COLORS.up }, { label: "下跌", value: data.decliners ?? 0, color: CHART_COLORS.down }, { label: "平盘", value: data.unchanged ?? 0, color: CHART_COLORS.flat }]} /><div className={styles.donutLegend}>{[["上涨家数", data.advancers, data.advanceRatio, CHART_COLORS.up], ["下跌家数", data.decliners, data.declineRatio, CHART_COLORS.down], ["平盘家数", data.unchanged, data.unchangedRatio, CHART_COLORS.flat]].map(([label, count, ratio, color]) => <div key={String(label)}><i style={{ background: String(color) }} /><span>{String(label)}</span><strong>{formatCount(count as number | null)}</strong><em>{ratio === null ? "暂无" : percent((ratio as number) * 100)}</em></div>)}</div></div><p className={styles.helper}>全市场 {formatCount(data.total)} 只 · 覆盖率 {data.coverageRatio === null ? "暂无" : `${formatNumber(data.coverageRatio * 100)}%`}</p>{data.limitMethod ? <p className={styles.helper}>{data.limitMethod}</p> : null}</> : <div className={styles.empty}>市场广度暂不可用</div>}</ModuleCard>; }

export function TurnoverCard({ data, pending, error, onRetry }: { data?: Breadth; pending: boolean; error: boolean; onRetry: () => void }) { const showHistory = (data?.turnoverHistory.length ?? 0) >= 2; return <ModuleCard title="两市成交额" pending={pending} error={error} onRetry={onRetry}><div data-testid="turnover-card">{data?.status === "available" ? <><div className={styles.turnoverLead}><span>今日成交额</span><strong>{data.turnover100mCny === null ? "暂无可比数据" : `${formatNumber(data.turnover100mCny)} 亿`}</strong></div><div className={styles.turnoverCompare}><span>较前一完整交易日</span><strong className={tone(data.turnoverChangeVsPreviousPct)}>{percent(data.turnoverChangeVsPreviousPct)}</strong></div>{showHistory ? <><p className={styles.helper}>近日成交额（亿元）</p><BarChart points={data.turnoverHistory.map((point) => ({ label: point.date, value: point.amount100mCny }))} /></> : null}{data.historyStatus === "intraday_not_comparable" ? <p className={styles.helper}>盘中累计成交额不与完整收盘日直接比较。</p> : null}{data.turnoverChangeVsPreviousPct === null && data.historyStatus !== "intraday_not_comparable" ? <p className={styles.helper}>历史对比数据积累中，暂无可比基准。</p> : null}</> : <div className={styles.empty}>成交额暂不可用</div>}</div></ModuleCard>; }

export function DistributionCard({ data, pending, error, onRetry }: { data?: Breadth; pending: boolean; error: boolean; onRetry: () => void }) { return <ModuleCard title="涨跌分布" meta="按涨跌幅分档" pending={pending} error={error} onRetry={onRetry}>{data?.status === "available" && data.distributionBins?.length ? <><Histogram bins={data.distributionBins.map((bin) => ({ label: bin.label, count: bin.count, tone: bin.key.includes("decliner") ? "down" : bin.key === "unchanged" ? "flat" : "up" }))} /><p className={styles.helper}>下跌 {formatCount(data.decliners)} · 平盘 {formatCount(data.unchanged)} · 上涨 {formatCount(data.advancers)} · 涨跌中位数 <b className={tone(data.medianPctChange)}>{percent(data.medianPctChange)}</b></p></> : <div className={styles.empty}>涨跌分布暂不可用</div>}</ModuleCard>; }

export function SectorCard({ data, pending, error, onRetry }: { data?: Sectors; pending: boolean; error: boolean; onRetry: () => void }) { return <ModuleCard title="板块热度" meta={data?.isStale === null ? <span className={styles.stale}>新鲜度待确认</span> : data?.isStale || data?.hasWarnings ? <span className={styles.stale}>缓存 / 延迟数据</span> : undefined} pending={pending} error={error} onRetry={onRetry}>{data?.items.length ? <div className={styles.sectorTable}><div className={styles.sectorTableHead}><span>排名</span><span>板块</span><span>涨跌幅</span><span>净流入</span></div>{data.items.slice(0, 8).map((item, index) => <div key={item.code}><span className={styles.rank}>{String(index + 1).padStart(2, "0")}</span><strong>{item.name}</strong><b className={tone(item.pctChange)}>{percent(item.pctChange)}</b><b className={tone(item.mainNetInflow100mCny)}>{item.mainNetInflow100mCny === null ? "暂无" : `${formatNumber(item.mainNetInflow100mCny)}亿`}</b></div>)}<p className={styles.helper}>来源：{data.source ?? "待确认"} · 数据时间 {formatDateTime(data.marketTimestamp ?? data.fetchedAt)}</p></div> : <div className={styles.empty}>暂无可确认板块数据</div>}</ModuleCard>; }

export function PersonalResearchSection({ overview, actions, changes, watchlist, overviewPending, overviewError, onRefresh }: { overview?: Overview; actions?: ResearchActions; changes?: ResearchChanges; watchlist?: WatchlistBrief; overviewPending: boolean; overviewError: boolean; onRefresh: () => void }) { return <><ModuleCard title="今日优先事项" meta={actions ? `${actions.items.length} 条确定性研究行动` : undefined} pending={overviewPending} error={overviewError} onRetry={onRefresh}>{overview?.themes.length ? <div className={styles.themeGrid}>{overview.themes.map((theme) => <article className={styles.themeCard} key={theme.key}><div className={styles.themeHead}><i className={theme.tone === "positive" ? styles.themePositive : theme.tone === "negative" ? styles.themeNegative : styles.themeNeutral} /><strong>{theme.title}</strong></div><p>{theme.summary}</p>{theme.basis ? <small>{theme.basis}</small> : null}</article>)}</div> : null}{overview?.priorityItems.length ? <div className={styles.priorityList}>{overview.priorityItems.map((item, index) => <article key={item.id}><div className={styles.priorityIndex}>{index + 1}</div><div><div className={styles.itemTitle}><strong>{item.symbol ? <Link to={`/stocks/${encodeURIComponent(item.symbol)}`}>{item.title}</Link> : item.title}</strong><span>{priorityKind(item.kind)}</span></div>{item.detail ? <p>{item.detail}</p> : null}<small>{item.rankReason ?? "由后端确定性规则排序"}</small></div></article>)}</div> : <div className={styles.empty}>{overview?.priorityEmptyMessage ?? "当前没有需要立即处理的个人研究事项。"}</div>}<div className={styles.personalMeta}>{watchlist?.requested === 0 ? "关注列表为空" : watchlist ? `关注 ${watchlist.requested} 项 · 数据可用 ${watchlist.available} 项` : "关注状态读取中"}</div></ModuleCard><ModuleCard title="我的股票新变化" pending={false} error={false} onRetry={() => undefined}>{changes?.items.length ? <div className={styles.changeList}>{changes.items.slice(0, 6).map((item) => <article key={item.id}><div><strong>{item.symbol ? <Link to={`/stocks/${encodeURIComponent(item.symbol)}`}>{item.symbol}</Link> : "组合研究"}</strong><span>{changeEventType(item.eventType)}{item.severity ? ` · ${item.severity}` : ""}</span></div><p>{item.summary}</p><small>{item.dataAsOf ?? "数据日期待确认"}</small></article>)}</div> : <div className={styles.empty}>暂无研究变化</div>}</ModuleCard></>; }

const GLOBAL_INDEX_ORDER = ["^GSPC", "^IXIC", "^DJI"] as const;
const LIVE_MARKET_ORDER = ["dollar_index", "london_gold", "brent_crude", "us10y_yield"] as const;
export function GlobalMarketCard({ indices, markets, pending, error, onRetry }: { indices?: GlobalIndices; markets?: LiveMarkets; pending: boolean; error: boolean; onRetry: () => void }) { const rows = GLOBAL_INDEX_ORDER.flatMap((symbol) => { const item = indices?.items.find((candidate) => candidate.symbol === symbol); return item ? [item] : []; }); const live = LIVE_MARKET_ORDER.flatMap((key) => { const item = markets?.items.find((candidate) => candidate.key === key); return item ? [item] : []; }); return <ModuleCard title="全球市场观察" pending={pending} error={error} onRetry={onRetry}>{rows.length || live.length ? <div className={styles.globalTable}><div className={styles.sectorTableHead}><span>指数</span><span>最新价</span><span>涨跌幅</span></div>{rows.map((item) => <div key={item.symbol}><strong>{item.name}</strong><span>{formatNumber(item.latestClose)}</span><b className={tone(item.return1dPct)}>{percent(item.return1dPct)}</b></div>)}{live.map((item) => <div key={item.key}><strong>{item.name}</strong><span>{item.latestPrice === null ? "暂无" : item.currency === "PCT" ? `${formatNumber(item.latestPrice)}%` : `${formatNumber(item.latestPrice)}${item.currency ? ` ${item.currency}` : ""}`}</span><b className={tone(item.pctChange)}>{percent(item.pctChange)}</b></div>)}</div> : <div className={styles.empty}>全球市场数据暂不可用</div>}</ModuleCard>; }

export function DataHealthBar({ data, pending, error, onRetry }: { data?: DataHealth; pending: boolean; error: boolean; onRetry: () => void }) { return <ModuleCard title="数据健康状态" pending={pending} error={error} onRetry={onRetry}><div className={styles.health}>{data ? <><strong>{data.userLabel}</strong><span>健康 {data.summary.healthy} · 关注 {data.summary.attention} · 关键 {data.summary.critical}</span></> : <span>暂无数据健康状态</span>}</div></ModuleCard>; }
