import {
  parseLiZongBacktest,
  parseLiZongCandidates,
  parseLiZongRunLatest,
  parseScreenerProfiles,
  parseStockScreen,
  type LiZongBacktest,
  type LiZongCandidates,
  type LiZongRunLatest,
  type ScreenerProfiles,
  type StockScreen,
} from "./adapters";

export function profilesPayload() {
  return {
    items: [
      {
        key: "quality",
        label: "经营改善候选",
        description: "先约束市值和估值口径，再核验最新财报中的营收、净利润与 ROE 是否同时为正。",
        sort_rule: "按最新财报营收同比从高到低排列；不计算综合分。",
        default_filters: {
          min_market_cap_yi: 50,
          min_pe_ttm: 0.01,
          max_pe_ttm: 80,
          min_revenue_yoy: 0,
          min_net_profit_yoy: 0,
          min_roe: 0,
        },
      },
      {
        key: "trend",
        label: "相对行业增强候选",
        description: "筛选近 5 日、20 日均为正，且近 20 日跑赢所属行业样本均值的股票。",
        sort_rule: "按近 20 日相对行业超额收益从高到低排列；不计算综合分。",
        default_filters: {
          min_market_cap_yi: 30,
          min_return_5d: 0,
          min_return_20d: 0,
          min_industry_excess_20d: 0,
          min_volume_ratio: 0.8,
          max_turnover_rate: 25,
        },
      },
    ],
    boundary: "选股功能用于生成可解释的研究候选，不构成推荐或交易建议。",
  };
}

export function screenPayload() {
  return {
    type: "stock_screen",
    status: "ready",
    profile: {
      key: "quality",
      label: "经营改善候选",
      description: "先约束市值和估值口径，再核验最新财报中的营收、净利润与 ROE 是否同时为正。",
      sort_rule: "按最新财报营收同比从高到低排列；不计算综合分。",
    },
    market: "all",
    rules: [
      { field: "股票状态", operator: "排除", value: "ST / *ST", reason: "降低特殊处理和退市风险对首轮研究候选的干扰。" },
      { field: "总市值下限", operator: ">=", value: 50, unit: "亿元", reason: "用户可见、可修改的确定性筛选条件。" },
      { field: "ROE 下限", operator: ">=", value: 0, unit: "%", reason: "用户可见、可修改的确定性筛选条件。" },
    ],
    effective_filters: { min_market_cap_yi: 50, min_roe: 0, exclude_st: true, min_listed_days: 180 },
    universe: {
      listed_input: 5532,
      expected_listed: 5537,
      market_coverage: 5532,
      after_common_rules: 5231,
      after_market_rules: 1754,
      valuation_coverage: 3994,
      financial_candidate_pool: 1754,
      financials_checked: 1204,
      matched: 2,
      represents_full_market: false,
    },
    warnings: ["财务覆盖未覆盖全市场，结果不代表全市场。"],
    data_contract: {
      contract_version: "stock_screen_data_v1",
      as_of: {
        market_date: "2026-08-05",
        generated_at: "2026-08-06T09:28:21+00:00",
        return_5d_base_date: "2026-07-29",
        return_20d_base_date: "2026-07-08",
        financial_report_periods: ["2026-03-31"],
      },
      representation: {
        coverage_status: "constrained",
        represents_full_market: false,
        note: "估值字段覆盖不足；财务核验仅覆盖候选池。",
        actual_scope_label: "A股完整行情范围，财务或规则约束样本",
      },
    },
    items: [
      {
        ts_code: "600549.SH",
        internal_symbol: "600549.SS",
        name: "厦门钨业",
        industry: "小金属",
        market: "主板",
        list_date: "2002-11-07",
        metrics: {
          latest_close: 53.72,
          pct_change: 8.789,
          total_mv_yi: 852.8511,
          circ_mv_yi: 834.7723,
          pe_ttm: 28.1155,
          pb: 4.6603,
          ps_ttm: 1.5915,
          turnover_rate_pct: 7.1545,
          volume_ratio: 2.01,
          return_5d_pct: 13.4051,
          return_20d_pct: -15.3883,
          industry_excess_20d_pct: -10.1551,
          industry_avg_return_20d_pct: -5.2331,
        },
        financials: {
          status: "available",
          coverage_status: "sufficient",
          report_period: "2026-03-31",
          announcement_date: "2026-04-24",
          revenue_yoy: 86.9907,
          net_profit_yoy: 189.1356,
          roe: 6.2352,
          gross_margin: 21.0038,
          net_margin: 10.6849,
          debt_to_assets: 55.617,
        },
        coverage_status: { financial_quality: "sufficient", valuation: "sufficient", market_and_trend: "sufficient" },
        matched_reasons: ["营收同比 86.99%、净利润同比 189.14% 同时为正", "ROE 6.24% 达到下限"],
        missing_fields: [],
        missing_reasons: [],
        not_applicable_fields: [],
        limitations: [],
        attention_flags: [],
        research_focus: "营收同比 86.99%、净利润同比 189.14% 同时为正。",
        evidence_times: {
          market_date: "2026-08-05",
          financial_report_period: "2026-03-31",
          financial_announcement_date: "2026-04-24",
        },
      },
      {
        ts_code: "000001.SZ",
        internal_symbol: "000001.SZ",
        name: "平安银行",
        industry: "银行",
        market: "主板",
        list_date: "1991-04-03",
        metrics: {
          latest_close: 12.34,
          pct_change: 0,
          total_mv_yi: 2183.1658,
          circ_mv_yi: 2183.1658,
          pe_ttm: 5.4,
          pb: 0.55,
          ps_ttm: 1.2,
          turnover_rate_pct: 0.8,
          volume_ratio: 0.9,
          return_5d_pct: -1.25,
          return_20d_pct: 3.4,
          industry_excess_20d_pct: 1.1,
          industry_avg_return_20d_pct: 2.3,
        },
        financials: null,
        coverage_status: { financial_quality: "insufficient", valuation: "sufficient", market_and_trend: "sufficient" },
        matched_reasons: ["估值与流动性约束通过"],
        missing_fields: ["revenue_yoy", "net_profit_yoy"],
        missing_reasons: ["最新财报尚未取得，按缺失处理而非按 0 处理。"],
        not_applicable_fields: [],
        limitations: ["财务字段缺失时不给经营结论。"],
        attention_flags: [],
        research_focus: null,
        evidence_times: {
          market_date: "2026-08-05",
          financial_report_period: null,
          financial_announcement_date: null,
        },
      },
    ],
    boundary: "这是可解释的研究候选筛选，不构成投资建议。",
  };
}

export function liZongCandidatesPayload() {
  return {
    status: "ready",
    strategy: {
      strategy_id: "li_zong",
      name: "李总策略",
      boundary: "不自动交易，不生成平台买卖指令。",
      version: {
        rules: [
          { rule_id: "LZ-F-01", group: "fundamental", label: "总市值严格大于150亿元" },
          { rule_id: "LZ-F-02", group: "fundamental", label: "连续五个完整年度ROE达标" },
          { rule_id: "LZ-C-01", group: "character", label: "近一年至少6次收盘涨停" },
          { rule_id: "LZ-T-01", group: "trigger", label: "当日收盘涨停" },
        ],
      },
    },
    counts: { total: 3, qualified: 1, triggered: 0, not_qualified: 1, data_incomplete: 1, invalidated: 0 },
    funnel: {
      starting_count: 5374,
      final_candidate_count: 1,
      as_of_date: "2026-08-05",
      scope: "sequential_rule_intersection",
      boundary: "漏斗按固定规则顺序展示逐步交集，只说明当前截面为何收窄。",
      steps: [
        { rule_id: "LZ-F-01", label: "总市值严格大于150亿元", removed_at_step: 4272, remaining_count: 1102 },
        { rule_id: "LZ-F-02", label: "连续五个完整年度ROE达标", removed_at_step: 891, remaining_count: 211 },
      ],
    },
    data_meta: {
      latest_as_of_date: "2026-08-05",
      universe_count: 5537,
      coverage_ratio: 0.970562,
      full_market_coverage: false,
      remaining_symbols: 163,
    },
    items: [
      {
        id: "cand-1",
        symbol: "600519.SH",
        internal_symbol: "600519.SS",
        name: "贵州茅台",
        industry: "白酒",
        market: "主板",
        as_of_date: "2026-08-05",
        evaluation_status: "qualified",
        previous_status: "not_qualified",
        candidate_qualified: true,
        triggered_rule_ids: [],
        matched_reasons: ["LZ-F-01 已通过", "LZ-F-02 已通过"],
        limitations: [],
        summary: {
          market_cap_yi: 2183.17,
          roe_min_pct: 24.8,
          annual_roe_years: 5,
          annual_limit_up_count: 0,
          recent_limit_up_count: 0,
          non_natural_holder_count: 10,
        },
        rule_results: [
          { rule_id: "LZ-F-01", status: "passed", source: "Tushare Pro:daily_basic", evidence_date: "2026-08-05", report_period: null, limitations: [] },
          { rule_id: "LZ-F-02", status: "passed", source: "Tushare Pro:fina_indicator", evidence_date: null, report_period: "2025-12-31", limitations: [] },
          { rule_id: "LZ-C-01", status: "failed", source: "Tushare Pro:daily", evidence_date: "2026-08-05", report_period: null, limitations: [] },
          { rule_id: "LZ-T-01", status: "failed", source: "Tushare Pro:daily", evidence_date: "2026-08-05", report_period: null, limitations: [] },
        ],
      },
      {
        id: "cand-2",
        symbol: "000001.SZ",
        internal_symbol: "000001.SZ",
        name: "平安银行",
        industry: "银行",
        market: "主板",
        as_of_date: "2026-08-05",
        evaluation_status: "not_qualified",
        previous_status: "not_qualified",
        candidate_qualified: false,
        triggered_rule_ids: [],
        matched_reasons: ["LZ-F-01 已通过"],
        limitations: [],
        summary: {
          market_cap_yi: 2183.1658,
          roe_min_pct: 8.1514,
          annual_roe_years: 5,
          annual_limit_up_count: 0,
          recent_limit_up_count: 0,
          non_natural_holder_count: 10,
        },
        rule_results: [
          { rule_id: "LZ-F-01", status: "passed", source: "Tushare Pro:daily_basic", evidence_date: "2026-08-05", report_period: null, limitations: [] },
          { rule_id: "LZ-F-02", status: "failed", source: "Tushare Pro:fina_indicator", evidence_date: null, report_period: "2025-12-31", limitations: [] },
        ],
      },
      {
        id: "cand-3",
        symbol: "300750.SZ",
        internal_symbol: "300750.SZ",
        name: "宁德时代",
        industry: "电池",
        market: "创业板",
        as_of_date: "2026-08-05",
        evaluation_status: "data_incomplete",
        previous_status: null,
        candidate_qualified: false,
        triggered_rule_ids: [],
        matched_reasons: ["LZ-F-01 已通过"],
        limitations: ["上市后量价历史不足，无法完成全部规则核验。"],
        summary: {
          market_cap_yi: 11500.5,
          roe_min_pct: null,
          annual_roe_years: null,
          annual_limit_up_count: null,
          recent_limit_up_count: null,
          non_natural_holder_count: null,
        },
        rule_results: [
          { rule_id: "LZ-F-01", status: "passed", source: "Tushare Pro:daily_basic", evidence_date: "2026-08-05", report_period: null, limitations: [] },
          { rule_id: "LZ-F-02", status: "data_incomplete", source: "Tushare Pro:fina_indicator", evidence_date: null, report_period: null, limitations: ["缺少五年完整 ROE。"] },
        ],
      },
    ],
    boundary: "当前页面只读取后台已发布快照，不触发新筛选任务。",
  };
}

export function liZongRunLatestPayload() {
  return {
    strategy_id: "li_zong",
    run: {
      id: "87f85e55-a406-43d8-8f50-b6322f03ea21",
      status: "partial",
      as_of_date: "2026-08-05",
      run_scope: "universe_batch",
      universe_count: 5537,
      prefiltered_count: 1265,
      coverage_ratio: 0.970562,
      processed_count: 10,
      qualified_count: 0,
      triggered_count: 0,
      incomplete_count: 0,
      invalidated_count: 0,
      error: null,
      started_at: "2026-08-06T09:24:53+00:00",
      finished_at: "2026-08-06T09:24:57+00:00",
      warnings: ["仍有 165 只可深度核验股票等待补齐数据。"],
    },
    coverage: {
      status: "stable",
      as_of_date: "2026-08-05",
      coverage_ratio: 0.970562,
      full_market_coverage: false,
      deep_check_complete: false,
      evaluated_symbols: 5374,
      remaining_symbols: 163,
    },
  };
}

export function liZongBacktestPayload() {
  const points = [
    { trade_date: "2025-07-21", nav: 1, benchmark_nav: 1, holding_count: 0, benchmark_exposed: true },
    { trade_date: "2025-10-21", nav: 1.08, benchmark_nav: 1.03, holding_count: 1, benchmark_exposed: true },
    { trade_date: "2026-01-21", nav: 0.96, benchmark_nav: 1.01, holding_count: 1, benchmark_exposed: true },
    { trade_date: "2026-04-21", nav: 1.15, benchmark_nav: 1.06, holding_count: 2, benchmark_exposed: true },
    { trade_date: "2026-08-03", nav: 1.281, benchmark_nav: 1.112, holding_count: 1, benchmark_exposed: true },
  ];
  return {
    strategy_id: "li_zong",
    strategy_version: "li_zong_v1",
    parameter_version: "li_zong_v1_default",
    backtest_version: "li_zong_equal_weight_v1",
    portfolio_version: "li_zong_2w_no_cost_full_benchmark_v5",
    selected_period: "1y",
    period_label: "近1年",
    status: "ready",
    assumptions: {
      benchmark: "沪深300（按完整回测区间连续计算）",
      weighting: "每次换仓后对可成交候选等资金权重。",
      rebalance: "候选集合变化后，最早于下一完整交易日开盘换仓。",
      cost_bps_per_side: 0,
      price_basis: "复权因子调整后的开盘价和收盘价。",
      cash_policy: "候选为空时持有现金，现金收益按 0 处理。",
      selection: "李总策略9条候选规则全部通过。",
    },
    progress: {
      status: "ready",
      phase: "ready",
      label: "近1年",
      result_as_of_date: "2026-08-03",
      market_data_ratio: 0.996032,
      available_market_days: 251,
      required_market_days: 252,
    },
    result: {
      status: "ready",
      period: "1y",
      period_label: "近1年",
      start_date: "2025-07-21",
      end_date: "2026-08-03",
      trading_days: 252,
      period_return_pct: 28.1046,
      annualized_return_pct: 27.0181,
      annualized_volatility_pct: 51.3464,
      max_drawdown_pct: -32.7614,
      benchmark_return_pct: 11.1996,
      benchmark_annualized_return_pct: 10.7943,
      excess_return_pct: 16.9051,
      eligible_symbol_count: 1947,
      complete_symbol_count: 1619,
      incomplete_symbol_count: 328,
      data_coverage_ratio: 0.831536,
      ever_selected_symbol_count: 29,
      selection_update_count: 21,
      total_turnover_pct: 2866.6667,
      trading_cost_bps_per_side: 0,
      generated_at: "2026-08-04T05:48:10+00:00",
      data_version: "c592af7e8c2744a84e9222e8e30c3a5460ecfef7ea006af8dafdee04ac447e7e",
      boundary: "回测严格使用每个历史交易日当时可见的候选状态。",
      data_coverage_boundary: "数据缺口股票的逐日状态按数据不可得处理。",
      points,
    },
    boundary: "回测严格使用每个历史交易日当时可见的候选状态。",
  };
}

export const parsedProfiles = (): ScreenerProfiles => parseScreenerProfiles(profilesPayload());
export const parsedScreen = (): StockScreen => parseStockScreen(screenPayload());
export const parsedLiZongCandidates = (): LiZongCandidates => parseLiZongCandidates(liZongCandidatesPayload());
export const parsedLiZongRunLatest = (): LiZongRunLatest => parseLiZongRunLatest(liZongRunLatestPayload());
export const parsedLiZongBacktest = (): LiZongBacktest => parseLiZongBacktest(liZongBacktestPayload());
